plugins {
    id 'java'
    id 'application'
    id 'org.graalvm.buildtools.native' version '0.10.3'   // or latest compatible
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.graalvm.polyglot:polyglot:25.0.1'
    implementation 'org.graalvm.python:python:25.0.1'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'org.example.App'      // make sure this matches your actual class
}

run {
    jvmArgs '-Dpolyglot.engine.WarnInterpreterOnly=false'
    jvmArgs '-Dpolyglot.log.file=graal.log'
}
