plugins {
    id 'java'
    id 'application'
    id "org.graalvm.python" version "25.0.1"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.graalvm.polyglot:polyglot:25.0.1"
    implementation "org.graalvm.polyglot:python:25.0.1"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

graalPy {
    packages = ["numpy==2.1.0", "termcolor==2.2"]
}

application {
    mainClass = 'org.example.App'   // <--- replace with your main class
}

run {
    jvmArgs '-Dpolyglot.engine.WarnInterpreterOnly=false'
    jvmArgs '-Dpolyglot.log.file=graal.log'
}