/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    // FXGL game framework
    implementation("com.github.almasb:fxgl:17.3")
    // Ensure platform-specific JavaFX native libraries are available at runtime
    val osName = System.getProperty("os.name").lowercase()
    val javafxPlatform = when {
        osName.contains("win") -> "win"
        osName.contains("mac") -> "mac"
        osName.contains("linux") -> "linux"
        else -> "win"
    }
    val fxVersion = "20"
    // compile-time (API) dependencies so JavaFX packages (javafx.scene.*) are available to the compiler
    implementation("org.openjfx:javafx-controls:$fxVersion")
    implementation("org.openjfx:javafx-fxml:$fxVersion")
    implementation("org.openjfx:javafx-media:$fxVersion")
    implementation("org.openjfx:javafx-graphics:$fxVersion")

    // runtime-only platform-specific native libraries (DLLs / .so / .dylib)
    runtimeOnly("org.openjfx:javafx-controls:$fxVersion:$javafxPlatform")
    runtimeOnly("org.openjfx:javafx-fxml:$fxVersion:$javafxPlatform")
    runtimeOnly("org.openjfx:javafx-media:$fxVersion:$javafxPlatform")
    runtimeOnly("org.openjfx:javafx-graphics:$fxVersion:$javafxPlatform")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        // Use Java 17 for compatibility with FXGL 17.x
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

// Ensure the application run task uses the Java toolchain launcher (so it runs with Java 17)
// and add a default JVM arg to prefer software rendering if the native pipeline isn't available.
application {
    applicationDefaultJvmArgs = listOf(
        "-Dprism.order=sw",
        "-Dprism.forceGPU=false",
        "-Dprism.verbose=true",
        "-Dprism.text=t2k"
    )
}

tasks.withType(org.gradle.api.tasks.JavaExec::class.java).configureEach {
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(org.gradle.jvm.toolchain.JavaLanguageVersion.of(17))
    })
}
