/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        // App is a GameApplication (FXGL); the generated template expected a getGreeting() method
        // Replace that check with a simple non-null sanity check for the App instance.
        assertNotNull(classUnderTest, "app instance should be created");
    }
}
